// Generated by using rustinr::rustrize() -> do not edit by hand

#include <Rinternals.h>
#include <R.h>

extern SEXP rustr_from_tson(SEXP rbytes);
SEXP rtson_from_tson(SEXP rbytes){ return(rustr_from_tson(rbytes));}
