// Generated by using rustinr::rustrize() -> do not edit by hand

use super::*;

#[no_mangle]
pub extern "C" fn rustr_to_tson(object : SEXP)->SEXP{

 let object_ : SEXP = unwrapr!( SEXP::rnew(object) );
 let res  = unwrapr!( to_tson(object_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

#[no_mangle]
pub extern "C" fn rustr_from_tson(rbytes : SEXP)->SEXP{

 let rbytes_ : RawVec = unwrapr!( RawVec::rnew(rbytes) );
 let res  = unwrapr!( from_tson(rbytes_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

#[no_mangle]
pub extern "C" fn rustr_to_json(object : SEXP)->SEXP{

 let object_ : SEXP = unwrapr!( SEXP::rnew(object) );
 let res  = unwrapr!( to_json(object_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

#[no_mangle]
pub extern "C" fn rustr_from_json(data : SEXP)->SEXP{

 let data_ : String = unwrapr!( String::rnew(data) );
 let res  = unwrapr!( from_json(data_));

 let res_sexp : SEXP = unwrapr!(res.intor());

 return res_sexp;
}

